"""Utility functions for audio processing."""

import logging
from pydub import AudioSegment

logger = logging.getLogger(__name__)


def wave_write(
    file: str, data: bytes, sample_width=2, sample_channels=1, sample_rate=16000
):
    """Writes WAVE-encoded audio data to a file path, or file-like object.

    Creates mono-channel audio audio at 16kHz, which is what is supported by
    EdgeTX / OpenTX radios, and is output from audio generated by `polly_process()`.

    Args:
        file (string/file-like object): File path to write audio data to.
        data (bytes): Audio data to write.
        sample_width (int, optional): Sample width in bytes. Defaults to 2.
        sample_channels (int, optional): Number of audio channels. Defaults to 1.
        sample_rate (int, optional): Sample rate in Hz. Defaults to 16000.

    Raises:
        IOError

    Example:
        ```python
        >>> from txsoundgen.audio import wave_write
        >>> wave_write('test.wav', b'00')
        'test.wav'
        ```
    """
    output_rate = 16000

    # https://github.com/jiaaro/pydub/blob/master/API.markdown
    sound = AudioSegment(
        data=data,
        sample_width=sample_width,
        frame_rate=sample_rate,
        channels=sample_channels,
    )
    sound.export(
        file, format="wav", bitrate="16k", parameters=["-ar", str(output_rate)]
    )
    logger.debug('Wrote audio data to "%s"', str(file))
    return file
